# Generated by Django 3.2 on 2021-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarpost',
            name='duplicate',
            field=models.TextField(),
        ),
    ]
