# Generated by Django 3.2 on 2021-05-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210520_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
